settings:
  title: 'Peer Studios Status'
  url: 'https://status.peerstudios.net' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: peerstudios.net
    name: Peer Studios
    description: 'Peer Studios main server'
    url: 'https://peerstudios.net/'
    method: GET
    expectStatus: 200
    followRedirect: false

  - id: chimu.moe
    name: Chimu frontend
    description: 'chimu.moe osu! beatmap mirror'
    url: 'https://chimu.moe/'
    method: GET
    expectStatus: 200
    followRedirect: true
    
  - id: api.chimu.moe
    name: Chimu API
    description: 'chimu.moe osu! beatmap mirror'
    url: 'https://api.chimu.moe/'
    method: GET
    expectStatus: 200
    followRedirect: true

  - id: enjuu.click
    name: Enjuu frontend
    description: 'Enjuu osu! private server'
    url: 'https://enjuu.click/'
    method: GET
    expectStatus: 200
    followRedirect: false

  - id: c.enjuu.click
    name: Enjuu backend
    description: 'Enjuu osu! private server'
    url: 'https://c.enjuu.click/'
    method: GET
    expectStatus: 200
    followRedirect: false

